version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "0.0.0.0:${APPLICATION_PORT:-8080}:80"
    volumes:
      - ./docker/conf.d:/etc/nginx/conf.d
      - .:/var/www
    links:
      - php

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-user}
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
