# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\UserInterface\Controller\:
        resource: '../src/UserInterface/Controller/'

    App\Infrastructure\DatabaseQuestionRepository:

    App\Domain\GetRandomQuestionsQuery:
        alias: App\Infrastructure\DatabaseQuestionRepository

    App\Domain\FindQuestionsByIdsQuery:
        alias: App\Infrastructure\DatabaseQuestionRepository

    App\Infrastructure\DatabaseAnswerRepository:

    App\Domain\FindAnswersByIdsQuery:
        alias: App\Infrastructure\DatabaseAnswerRepository

    App\Domain\UserTestResultGateway:
        class: App\Infrastructure\DatabaseUserTestResultGateway

    App\UserInterface\ResponseShowUserPresenter:
        shared: false

    App\UserInterface\ResponseCheckUserTestPresenter:
        shared: false

    App\Domain\UseCase\ShowUserTest\ShowUserTestInteractor:

    App\Domain\UseCase\CheckUserTest\CheckUserTestInteractor:
